User.create(username: "Alligator Hero", email:"example@domain.com", password: "password")
#Dummy User For tests
#Category Seed Info: Admin Edit Only
    song = Category.find_or_create_by(name: "Song", definition: "A short poem or other set of words set to music or meant to be sung.")
    prose = Category.find_or_create_by(name: "Prose", definition: "Written or spoken language in its ordinary form, without metrical structure.")
    epic = Category.find_or_create_by(name: "Epic", definition: "A long poem, typically one derived from ancient oral tradition, narrating the deeds and adventures of heroic or legendary figures or the history of a nation.")
    poem = Category.find_or_create_by(name: "Poem", definition: "A piece of writing that partakes of the nature of both speech and song that is nearly always rhythmical, usually metaphorical, and often exhibits such formal elements as meter, rhyme, and stanzaic structure.")
    lyric = Category.find_or_create_by(name: "Lyric", definition: "Expressing the writer's emotions, usually briefly and in stanzas or recognized forms.")
    autobiography = Category.find_or_create_by(name: "Autobiography", definition: "An account of a person's life written by that person.")
    biography = Category.find_or_create_by(name: "Biography", definition: "An account of someone's life written by someone else.")
    short_story = Category.find_or_create_by(name: "Short Story", definition: "A story with a fully developed theme but significantly shorter and less elaborate than a novel.")
    novel = Category.find_or_create_by(name: "Novel Quote", definition: "A ictitious prose narrative of book length, typically representing character and action with some degree of realism.")
    fable = Category.find_or_create_by(name: "Fable", definition: "A short story, typically with animals as characters, conveying a moral.")
    religious_text = Category.find_or_create_by(name: "Religious Text", definition: "Writing that is venerated for the worship of a deity")

#Author Seed Info
    john_donne = Author.find_or_create_by(user_id: 1, name: "John Donne", birth: 1572 , death: 1631, biography: "John Donne was an English poet, scholar, soldier and secretary born into a recusant family, who later became a cleric in the Church of England.[3] Under royal patronage, he was made Dean of St Paul's Cathedral in London (1621–1631).[2] He is considered the preeminent representative of the metaphysical poets. His poetical works are noted for their metaphorical and sensual style and include sonnets, love poems, religious poems, Latin translations, epigrams, elegies, songs, and satires. He is also known for his sermons.")
    robert_frost = Author.find_or_create_by(user_id: 1, name: "Robert Frost", birth: 1874, death: 1963, biography: "Robert Lee Frost was an American poet. His work was initially published in England before it was published in the United States. Known for his realistic depictions of rural life and his command of American colloquial speech,[2] Frost frequently wrote about settings from rural life in New England in the early 20th century, using them to examine complex social and philosophical themes.")
    maya_angelou = Author.find_or_create_by(user_id: 1, name: "Maya Angelou", birth: 1928, death: 2014, biography: "Maya Angelou = born Marguerite Annie Johnson; April 4, 1928 – May 28, 2014) was an American poet, memoirist, and civil rights activist. She published seven autobiographies, three books of essays, several books of poetry, and is credited with a list of plays, movies, and television shows spanning over 50 years. She received dozens of awards and more than 50 honorary degrees.[3] Angelou is best known for her series of seven autobiographies, which focus on her childhood and early adult experiences. The first, I Know Why the Caged Bird Sings (1969), tells of her life up to the age of 17 and brought her international recognition and acclaim.")
    beach_boys= Author.find_or_create_by(user_id: 1, name: "The Beach Boys", biography: "The Beach Boys are an American rock band formed in Hawthorne, California in 1961. The group's original lineup consisted of brothers Brian, Dennis, and Carl Wilson, their cousin Mike Love, and friend Al Jardine. Distinguished by their vocal harmonies, adolescent-oriented themes, and musical ingenuity, they are one of the most influential acts of the rock era. They drew on the music of older pop vocal groups, 1950s rock and roll, and black R&B to create their unique sound, and under Brian's direction, often incorporated classical or jazz elements and unconventional recording techniques in innovative ways.", birth: 1961, death: nil)
#Classic Seed Info  
    #song
    Classic.find_or_create_by(user_id: 1, author_id: beach_boys.id, category_id: song.id, title: "Wouldn't It Be Nice", content: "Wouldn't it be nice if we were older? Then we wouldn't have to wait so long And wouldn't it be nice to live together In the kind of world where we belong? You know it's gonna make it that much better When we can say goodnight and stay together Wouldn't it be nice if we could wake up In the morning when the day is new? And after having spent the day together Hold each other close the whole night through Happy times together we've been spending I wish that every kiss was never ending Oh, wouldn't it be nice? Maybe if we think and wish and hope and pray It might come true Baby, then there wouldn't be a single thing we couldn't do Oh, we could be married (oh, we could be married) And then we'd be happy (and then we'd be happy) Oh, wouldn't it be nice? You know it seems the more we talk about it It only makes it worse to live without it But let's talk about it Oh, wouldn't it be nice? Goodnight, my baby Sleep tight, my baby Goodnight, my baby Sleep tight, my baby", release_date: 1966 )
    #poems
    Classic.find_or_create_by(user_id: 1, author_id: john_donne.id, category_id: poem.id, release_date: 1624, title: "No Man Is An Island", translation: "An island no man is, entire of itself, a piece of the continent every man is, a part of the main. Washed away by the sea if a clod be, the less europe is. As well as if a promontory were. : any man’s death diminishes me as well as if a manor of thy friend’s or of thine own were, involved in mankind because I am, to know for whom the bell tolls; it tolls for thee and therefore never send.", content: "No man is an island, Entire of itself, Every man is a piece of the continent, A part of the main. If a clod be washed away by the sea, Europe is the less. As well as if a promontory were. As well as if a manor of thy friend’s Or of thine own were: Any man’s death diminishes me, Because I am involved in mankind, And therefore never send to know for whom the bell tolls; It tolls for thee.")
    Classic.find_or_create_by(user_id: 1, author_id: robert_frost.id, category_id: poem.id, release_date: 1923, title:"Stopping by Woods On a Snowy Evening", translation: "I think I know whose woods these are. In the village though; he will not see me stopping here to watch his woods fill up with snow his house is. Think it queer to stop without a farmhouse near between the woods and frozen lake the darkest evening of the year my little horse must. His harness bells a shake to ask if there is some mistake he gives. Of easy wind and downy flake the only other sound’s the sweep. Lovely the woods are, dark and deep, promises to keep but I have, before I sleep and miles to go, before I sleep and miles to go.", content: "Whose woods these are I think I know. His house is in the village though; He will not see me stopping here To watch his woods fill up with snow. My little horse must think it queer To stop without a farmhouse near Between the woods and frozen lake The darkest evening of the year. He gives his harness bells a shake To ask if there is some mistake. The only other sound’s the sweep Of easy wind and downy flake. The woods are lovely, dark and deep, But I have promises to keep, And miles to go before I sleep, And miles to go before I sleep.")
    Classic.find_or_create_by(user_id: 1, author_id: maya_angelou.id, category_id: poem.id, release_date: 1978, title:"Still I Rise", translation: "Me down in history with your bitter you may write, twisted lies, you may tread me in the very dirt but still, dust like, i’ll rise. My sassiness upset you does? You beset with gloom why are? I’ve got oil wells pumping in my living room ’cause I walk like. Moons and like suns just like, with the certainty of tides, hopes springing high just like, still i’ll rise. You want to see me broken did? Bowed head and lowered eyes? Down like teardrops shoulders falling. Weakened by my soulful cries. My haughtiness offend you does? It awful hard ’cause I laugh like i’ve got gold mines diggin’ in my own back yard don’t you take. Me with your words you may shoot, me with your eyes you may cut, you may kill me with your hatefulness, but still, air like, i’ll rise. My sexiness upset you does? It come as a surprise that I dance like i’ve got diamonds at the meeting of my thighs does? Up from a past that’s rooted in pain I rise i’m a black ocean out of the huts of history’s shame I rise, leaping and wide, I bear in the tide welling and swelling. Behind nights of terror and fear I rise into a daybreak that’s wondrously clear I rise bringing the gifts that my ancestors gave leaving, the dream and the hope of the slave I am. I rise I rise I rise.", content: "You may write me down in history With your bitter, twisted lies, You may tread me in the very dirt But still, like dust, I’ll rise. Does my sassiness upset you? Why are you beset with gloom? ’Cause I walk like I’ve got oil wells Pumping in my living room. Just like moons and like suns, With the certainty of tides, Just like hopes springing high, Still I’ll rise. Did you want to see me broken? Bowed head and lowered eyes? Shoulders falling down like teardrops. Weakened by my soulful cries. Does my haughtiness offend you? Don’t you take it awful hard ’Cause I laugh like I’ve got gold mines Diggin’ in my own back yard. You may shoot me with your words, You may cut me with your eyes, You may kill me with your hatefulness, But still, like air, I’ll rise. Does my sexiness upset you? Does it come as a surprise That I dance like I’ve got diamonds At the meeting of my thighs? Out of the huts of history’s shame I rise Up from a past that’s rooted in pain I rise I’m a black ocean, leaping and wide, Welling and swelling I bear in the tide. Leaving behind nights of terror and fear I rise Into a daybreak that’s wondrously clear I rise Bringing the gifts that my ancestors gave, I am the dream and the hope of the slave. I rise I rise I rise.")
    Classic.find_or_create_by(user_id: 1, author_id: robert_frost.id ,category_id: poem.id, release_date: 1920, title:"Fire and Ice", content: " Some say the world will end in fire, Some say in ice. From what I've tasted of desire I hold with those who favor fire. But if it had to perish twice, I think I know enough of hate To know that for destruction ice Is also great And would suffice.", translation: "Some say the world will end in fire,Some say in ice.Of desire I hold with those who favor fire, from what I've tasted.To perish twice, but if it had,I know enough of hate to know that for destruction ice is also great and would suffice, I think.   ")